from typing import List

def _get_opening_description(eco_code: str) -> str:
    """Descripciones técnicas de las aperturas"""
    descriptions = {
        'E00': "La Apertura Catalana combina desarrollo armónico con presión en el flanco de dama. Ideal para jugadores estratégicos que disfrutan de posiciones sólidas con potencial de ataque en el medio juego.",
        'A10': "La Apertura Inglesa es una estructura flexible que controla el centro con piezas menores. Permite transposiciones a múltiples sistemas y es popular entre jugadores posicionales.",
        'D02': "El Sistema Londres es una apertura universal que crea una estructura de peones sólida. Prioriza el desarrollo rápido y el control del centro con piezas en lugar de peones.",
        'C39': "El Gambito de Rey sacrifica un peón para obtener ventaja en desarrollo. Recomendado para jugadores tácticos que disfrutan de posiciones abiertas y dinámicas.",
        'C44': "La Apertura Escocesa busca el control central inmediato con 1.e4 e5 2.Cf3 Cc6 3.d4. Favorece a jugadores que prefieren posiciones abiertas con juego activo.",
        'C21': "El Gambito Danés ofrece dos peones por un rápido desarrollo. Ideal para jugadores agresivos que buscan ataques directos desde la apertura.",
        'C50': "La Apertura Italiana desarrolla piezas rápidamente hacia el centro. Combina principios clásicos con moderna teoría de desarrollo.",
        'C60': "La Apertura Española es una de las más estudiadas. Crea tensión central con 3.Ab5, llevando a estructuras ricas en estrategia.",
        'D00': "El Gambito de Dama combina desarrollo con presión en el centro. La variante 3.c4 crea dinámicas posiciones con posibilidades para ambos bandos.",
        'A20': "La Siciliana Invertida es una estructura simétrica donde el blanco adopta ideas de la Siciliana. Se caracteriza por 1.c4 c5, con enfoque en control central y contrajuego dinámico.",
        'A34': "La Variante Simétrica surge en la Apertura Inglesa con 1.c4 c5. Ambos bandos comparten estructuras similares, priorizando desarrollo equilibrado y planes estratégicos profundos.",
        'A17': "La Variante India combina elementos de la Apertura Inglesa y las Defensas Indias. Busca controlar el centro con piezas y preparar rupturas como ...d5 o ...e5.",
        'B10': "La Caro-Kann es una defensa sólida contra 1.e4. Con 1...c6, el negro busca estructuras estables y contrajuego en el flanco de dama.",
        'B20': "La Siciliana es la respuesta más agresiva a 1.e4. Con 1...c5, el negro genera tensión central y prepara ataques rápidos en el flanco de rey.",
        'C00': "La Francesa es una defensa posicional con 1...e6. Crea una estructura de peones cerrada y contrajuego basado en ...d5 y ...c5.",
        'D10': "La Eslava es una defensa sólida contra el Gambito de Dama. Con 1.d4 d5 2.c4 c6, el negro mantiene la tensión central y busca contrajuego en el flanco de dama.",
        'E12': "La India de Dama combina desarrollo rápido y control central con piezas. La jugada 1...b6 prepara un fianchetto del alfil de dama y estructuras flexibles.",
        'E60': "La India de Rey es una defensa hipermoderna con 1...g6. Prioriza el desarrollo rápido del alfil de rey y estructuras asimétricas con potencial de ataque en ambos flancos."
    }
    return descriptions.get(eco_code, "Descripción no disponible")

def _get_plans(eco_code: str) -> List[str]:
    """Planes estratégicos por apertura"""
    plans = {
        'E00': [
            "Desarrollar alfiles a g5 y f4",
            "Preparar e4 para controlar el centro",
            "Crear peones colgantes en d4 y e4"
        ],
        'A10': [
            "Controlar el centro con c4 y d3",
            "Desarrollar caballos a f3 y c3",
            "Preparar fianchetto de alfil en g2"
        ],
        'D02': [
            "Desarrollar alfiles a f4 y g5",
            "Crear peón en d4 con c3",
            "Mantener estructura de peones sólida"
        ],
        'C39': [
            "Aprovechar el desarrollo rápido",
            "Atacar el enroque enemigo con Dh5",
            "Mantener presión en columna f"
        ],
        'C44': [
            "Mantener tensión en el centro",
            "Desarrollar alfiles a c4 y b5",
            "Preparar enroque corto"
        ],
        'C21': [
            "Sacar máximo provecho de los peones entregados",
            "Desarrollar piezas con ganancia de tiempo",
            "Lanzar ataque rápido en el flanco rey"
        ],
        'C50': [
            "Desarrollar alfiles a c4 y b5",
            "Preparar enroque corto",
            "Crear tensión en e5"
        ],
        'C60': [
            "Mantener tensión con Ab5",
            "Preparar d4 para abrir el centro",
            "Desarrollar caballo a c3"
        ],
        'D00': [
            "Controlar el centro con peones",
            "Desarrollar alfiles a g5 y f4",
            "Preparar e4 para romper el centro"
        ],
        'A20': [
            "Desarrollar alfiles a g2 y b2",
            "Preparar rupturas centrales con d4",
            "Mantener simetría para presión posicional"
        ],
        'A34': [
            "Desarrollar alfiles a g2 y b2",
            "Evitar simplificaciones tempranas",
            "Preparar rupturas con d3 y e4"
        ],
        'A17': [
            "Desarrollar alfiles a g2 y b2",
            "Controlar el centro con Ae3 y Dd2",
            "Preparar rupturas con f4 o e5"
        ],
        'B10': [
            "Desarrollar alfiles a g4 y f5",
            "Soportar el avance ...d5 con ...Cc6",
            "Preparar enroque largo en posiciones cerradas"
        ],
        'B20': [
            "Desarrollar alfiles a c4 y b5",
            "Crear peones centrales con d4",
            "Preparar ataques con Dd2 y Tfd1"
        ],
        'C00': [
            "Desarrollar alfiles a e7 y d7",
            "Soportar el avance ...d5 con ...Cf6",
            "Preparar rupturas con ...c5 y ...f6"
        ],
        'D10': [
            "Desarrollar alfiles a g4 y f5",
            "Mantener la tensión con ...c5",
            "Preparar rupturas con ...e5 o ...b5"
        ],
        'E12': [
            "Desarrollar alfiles a b2 y g2",
            "Controlar el centro con Ce4 y Dc2",
            "Preparar rupturas con f4 o c5"
        ],
        'E60': [
            "Desarrollar alfiles a g7 y g2",
            "Atacar el centro con ...d5 y ...c5",
            "Preparar enroque corto y ataques en ambos flancos"
        ]
    }
    return plans.get(eco_code, [])

def _get_model_games(eco_code: str) -> List[str]:
        """Obtiene una lista de movimientos de una partida model para la apertura dada"""
        model_games = {
            'E00': [
                "Nf3", "Nf6",
                "c4", "e6",
                "g3", "d5",
                "d4", "Be7",
                "Bg2", "O-O",
                "O-O", "dxc4",
                "Qc2", "a6",
                "Qxc4", "b5",
                "Qc2", "Bb7",
                "Bd2", "Nc6",
                "e3", "Nb4",
                "Bxb4", "Bxb4",
                "a3", "Be7",
                "Nbd2", "Rc8",
                "b4", "a5",
                "Ne5", "Nd5",
                "Nb3", "axb4",
                "Na5", "Ba8",
                "Nac6", "Bxc6",
                "Nxc6", "Qd7",
                "Bxd5", "exd5",
                "axb4", "Rfe8",
                "Ra5", "Bf8",
                "Ne5", "Qe6",
                "Rxb5", "Rb8",
                "Rxb8", "Rxb8",
                "Qxc7", "Bd6",
                "Qa5", "Bxb4",
                "Rb1", "Qd6",
                "Qa4"
            ],
            'A10': [
                "c4", "e5",
                "Nc3", "Nf6",
                "Nf3", "Nc6",
                "g3", "d5",
                "cxd5", "Nxd5",
                "d3", "Be7",
                "Bg2", "Be6",
                "O-O", "O-O",
                "Bd2", "f5",
                "Rc1", "Nb6",
                "a3", "Kh8",
                "b4", "a5",
                "b5", "Nd4",
                "Nxd4", "exd4",
                "Na4", "Bxa3",
                "Ra1", "Bd6",
                "Bxb7", "f4",
                "Qc2", "Bh3",
                "Bxa8", "Qxa8",
                "Qc6", "Qxc6",
                "bxc6", "fxg3",
                "hxg3", "Bxf1",
                "Kxf1", "Bxg3",
                "Kg2", "Bd6",
                "Bxa5", "Nxa4",
                "Rxa4", "Ra8",
                "e3", "dxe3",
                "fxe3", "h5",
                "d4", "Re8",
                "Bd2", "Kh7",
                "Ra5", "Kg6",
                "Kf3", "Rf8+",
                "Ke2", "h4",
                "e4", "Be7",
                "Be3", "Rf6",
                "Rg5+", "Kf7",
                "d5", "Rd6",
                "Rf5+", "Ke8",
                "Bf4", "g6",
                "Bxd6", "gxf5",
                "Bxe7"
            ],
            'D02': [
                "d4", "e6",
                "Nf3", "f5",
                "Bf4", "Nf6",
                "e3", "Be7",
                "Bd3", "O-O",
                "Nbd2", "d6",
                "c3", "Nc6",
                "Qc2", "Qe8",
                "h3", "Bd7",
                "Bh2", "g6",
                "e4", "fxe4",
                "Nxe4", "Nxe4",
                "Bxe4", "d5",
                "Bd3", "Bd6",
                "Qe2", "Qe7",
                "O-O", "Bxh2+",
                "Kxh2", "Rf4",
                "Bb5", "Qd6",
                "g3", "Rf5",
                "Bxc6", "Bxc6",
                "Ne5", "Raf8",
                "f3", "Be8",
                "h4", "c5",
                "Rfe1", "cxd4",
                "cxd4", "Qb4",
                "Qf2", "g5",
                "hxg5", "Rxg5",
                "a3", "Qe7",
                "Rac1", "Rg7",
                "Qe3", "Bh5",
                "Kh3", "Qf6",
                "g4", "Be8",
                "Kg3", "Qd8",
                "Rh1", "Qb6",
                "Rh2", "Qd8",
                "Rh6", "Qd6",
                "Kg2", "Bg6",
                "Rc5", "Qb6",
                "Qc3", "Qd8",
                "Qc1", "Qf6",
                "Rc8", "Qe7",
                "Rxf8+", "Qxf8",
                "Rh1", "Qd8",
                "Qh6", "Qd6",
                "Qf4", "Qb6",
                "Rc1", "Qd8",
                "Kg3", "Be8",
                "Qh6", "Bg6",
                "Rc3", "Qf8",
                "Qc1", "Be8",
                "Rc8", "Re7",
                "Qg5+", "Kh8",
                "Nd3", "Qg7",
                "Qh5", "Qf8",
                "Qe5+", "Qg7",
                "Qb8", "Qf8",
                "Qxa7", "h5",
                "Qb8", "hxg4",
                "fxg4", "Kh7",
                "Rc7", "b5",
                "Nf4", "Kg8",
                "Rxe7", "Qxe7",
                "Qe5", "Kf7",
                "g5", "Bd7",
                "g6+"
            ],
            'C39': [
                "e4", "e5",
                "f4", "exf4",
                "Bc4", "Nf6",
                "Nc3", "Bb4",
                "Nge2", "d5",
                "exd5", "f3",
                "gxf3", "O-O",
                "d4", "Bh3",
                "Bg5", "Bg2",
                "Rg1", "Bxf3",
                "Qd2", "Be7",
                "O-O-O", "Bh5",
                "Rde1", "Nbd7",
                "Nf4", "Bg6",
                "h4", "Re8",
                "Qg2", "Bf8",
                "h5", "Bf5",
                "Ne6", "fxe6",
                "dxe6", "Kh8",
                "exd7", "Rxe1+",
                "Rxe1", "Bxd7",
                "h6", "Bc6",
                "d5", "Bd7",
                "Rf1", "b5",
                "Bb3", "Qe8",
                "d6", "Nh5",
                "Bf7", "Qe5",
                "Qxa8"
            ],
            'C44': [
                "e4", "e5",
                "Nf3", "Nc6",
                "d4", "exd4",
                "Nxd4", "Bc5",
                "Be3", "Qf6",
                "c3", "Nge7",
                "Bc4", "O-O",
                "O-O", "Bb6",
                "Nc2", "d6",
                "Bxb6", "axb6",
                "f4", "g5",
                "f5", "Ne5",
                "Be2", "Bd7",
                "c4", "g4",
                "Nc3", "h5",
                "Qd2", "Kh8",
                "Qf4", "Bc6",
                "Ne3", "Nd7",
                "Bxg4", "hxg4",
                "Nxg4", "Qh4",
                "Rf3", "Ng6",
                "Qe3", "Qxg4",
                "Qh6+", "Kg8",
                "Rh3", "Qxh3",
                "gxh3", "Nge5",
                "f6", "Nxf6",
                "Qxf6", "Rae8",
                "Kh1", "Ng6",
                "h4", "Re6",
                "Qg5", "Rfe8",
                "h5", "Re5",
                "Qh6", "Rxe4",
                "Nxe4", "Rxe4",
                "Kg1", "Ne5",
                "Qg5+", "Kh7",
                "Qf5+", "Kh6",
                "Rf1", "Re2",
                "Qf6+", "Kh7",
                "Qg5", "Be4",
                "h6", "Bg6",
                "h4", "Re4",
                "h5", "Rg4+",
                "Qxg4", "Nxg4",
                "hxg6+", "fxg6",
                "Rf7+", "Kxh6",
                "Rxc7", "Ne5",
                "Rxb7", "Nxc4",
                "b3"
            ],
            'C21': [
                "e4", "e5",
                "d4", "exd4",
                "c3", "dxc3",
                "Nxc3", "Bb4",
                "Bc4", "Bxc3+",
                "bxc3", "d6",
                "Qb3", "Qe7",
                "Ne2", "Nc6",
                "O-O", "Nf6",
                "Nd4", "Nxd4",
                "cxd4", "O-O",
                "Re1", "h6",
                "Ba3", "Ng4",
                "f3", "Nf6",
                "e5", "Nd7",
                "exd6", "Qf6",
                "dxc7", "Qxd4+",
                "Kh1", "Nc5",
                "Bxf7+", "Rxf7",
                "Bxc5", "Qf6",
                "Rad1", "b6",
                "Rd6", "Qf5",
                "Rd5", "Qf6",
                "Be7", "Rxe7",
                "Re7", "Kf8",
                "Re1", "Bb7",
                "Rd7", "Bc6",
                "Qb4+", "Kg8",
                "Qc4+", "Kh8",
                "Qxc6", "Rc8",
                "Rd8", "Rxd8",
                "cxd8=Q"
            ],
            'C50': [
                "e4", "e5",
                "Nf3", "Nc6",
                "Bc4", "Bc5",
                "Nc3", "Nf6",
                "d3", "d6",
                "Be3", "Bxe3",
                "fxe3", "Na5",
                "Bb3", "Nxb3",
                "axb3", "Ng4",
                "Qe2", "f6",
                "d4", "c6",
                "O-O-O", "Qe7",
                "h3", "Nh6",
                "g4", "Bd7",
                "Nh4", "g6",
                "Nf3", "Nf7",
                "Rdg1", "O-O-O",
                "b4", "Kb8",
                "Qf2", "Rdf8",
                "Qg3", "h6",
                "Rf1", "Nd8",
                "Rhg1", "Ne6",
                "Rf2", "Nc7",
                "Rgf1", "Rfg8",
                "Nh4", "Ne8",
                "b5", "Ka8",
                "bxc6", "bxc6",
                "Nf3", "g5",
                "Rg2", "h5",
                "b3", "Rh6",
                "Kb2", "Rgh8",
                "Qf2", "Nc7",
                "Ra1", "Rb8",
                "Qe2", "Rb7",
                "Rgg1", "Rh8",
                "Rad1", "hxg4",
                "hxg4", "Rc8",
                "Qd3", "Be6",
                "Nd2", "Nb5",
                "Ndb1", "Rbc7",
                "Na4", "Rb7",
                "Kc1", "Rcb8",
                "Rg2", "Rd7",
                "Nbc3", "Nc7",
                "d5", "cxd5",
                "exd5", "Bg8",
                "Qc4", "Rc8",
                "Kb2", "Rb8",
                "e4", "Rdd8",
                "Rf2", "Rf8",
                "Rdf1", "Bh7",
                "Rxf6", "Rxf6",
                "Rxf6", "Qxf6",
                "Qxc7", "Qh8",
                "Qc6+", "Rb7",
                "Nb5", "Kb8",
                "Qxd6+", "Kc8",
                "Qc6+"
            ],
            'C60': [
                "e4", "e5",
                "Nf3", "Nc6",
                "Bb5", "a6",
                "Ba4", "Nf6",
                "O-O", "Be7",
                "Re1", "b5",
                "Bb3", "d6",
                "c3", "O-O",
                "h3", "Bb7",
                "d4", "Re8",
                "Ng5", "Rf8",
                "Nf3", "Re8",
                "Nbd2", "Bf8",
                "Bc2", "g6",
                "a4", "Bg7",
                "d5", "Nb8",
                "Bd3", "bxa4",
                "Qxa4", "c6",
                "c4", "Qc7",
                "Nb3", "Nbd7",
                "Bd2", "Reb8",
                "Qa3", "Ne8",
                "dxc6", "Bxc6",
                "Na5", "Nc5",
                "b4", "Nxd3",
                "Qxd3", "Bd7",
                "Rac1", "Rd8",
                "Nh2", "Nf6",
                "Nf1", "Nh5",
                "Ne3", "Nf4",
                "Qa3", "Rdc8",
                "Nd5", "Nxd5",
                "exd5", "f5",
                "f4", "Re8",
                "Bc3", "exf4",
                "Bxg7", "Kxg7",
                "Qc3+", "Kg8",
                "c5", "Bb5",
                "Qd2", "g5",
                "Nb3", "Qf7",
                "cxd6", "Re4",
                "Nc5", "Rae8",
                "Ne6", "R8xe6",
                "dxe6", "Qxe6",
                "Rxe4", "fxe4",
                "Rc5", "h6",
                "Qd5"
            ],
            'D00': [
                "d4", "Nf6",
                "c4", "e6",
                "Nf3", "d5",
                "Nc3", "c6",
                "Bg5", "h6",
                "Bh4", "dxc4",
                "e4", "g5",
                "Bg3", "b5",
                "Be2", "b4",
                "Na4", "Nxe4",
                "Be5", "Nf6",
                "Nc5", "c3",
                "bxc3", "bxc3",
                "O-O", "Nbd7",
                "Nxd7", "Bxd7",
                "Qb3", "Bg7",
                "Qa3", "g4",
                "Ne1", "c5",
                "dxc5", "O-O",
                "Bxc3", "h5",
                "Rd1", "Nd5",
                "Bxg7", "Kxg7",
                "Bc4", "Bc6",
                "Nc2", "Qf6",
                "Nd4", "Ne7",
                "f3", "g3",
                "hxg3", "Rfd8",
                "Nxc6", "Nxc6",
                "Qe3", "Nd4",
                "g4", "Rac8",
                "g5", "Qf5",
                "Rxd4", "Qxc5",
                "Bxe6", "Rc6",
                "Re4", "Qxe3+",
                "Rxe3", "Rxe6",
                "Rxe6", "fxe6",
                "Re1", "Rd6",
                "Kh2", "Kg6",
                "f4", "Kf5",
                "Kg3", "h4+",
                "Kxh4", "Kxf4",
                "g6", "Rd8",
                "Rf1+", "Ke3",
                "Kg5", "e5",
                "g7"
            ],
            'A20': [
                "c4", "e5",
                "Nc3", "Nf6",
                "g3", "c6",
                "Nf3", "e4",
                "Nd4", "d5",
                "cxd5", "cxd5",
                "Bg2", "Nc6",
                "Nxc6", "bxc6",
                "d3", "exd3",
                "Qxd3", "Bb4",
                "O-O", "O-O",
                "Na4", "Re8",
                "a3", "Bd6",
                "Be3", "a5",
                "Rfe1", "Ba6",
                "Qc3", "Rb8",
                "Bd4", "Bb5",
                "b3", "Ne4",
                "Bxe4", "Rxe4",
                "f3", "Bxa4",
                "bxa4", "Re6",
                "Rab1", "Rc8",
                "Bc5", "Be5",
                "Qd2", "Rg6",
                "f4", "Bd6",
                "Rbc1", "h5",
                "Bxd6", "Qxd6",
                "e4", "h4",
                "Kg2", "hxg3",
                "hxg3", "Rb8",
                "exd5", "cxd5",
                "Re5", "d4",
                "Rb5", "Rxb5",
                "axb5", "Qd5+",
                "Kf2", "Rh6",
                "Rc8+", "Kh7",
                "Qd3+", "g6",
                "Qf3", "Rh2+"
            ],
            'A34': [
                "c4", "c5",
                "Nc3", "Nc6",
                "Nf3", "Nf6",
                "d4", "cxd4",
                "Nxd4", "e6",
                "e3", "Be7",
                "a3", "O-O",
                "b4", "d5",
                "Nxc6", "bxc6",
                "Bb2", "e5",
                "Qc2", "Bg4",
                "Be2", "Qc8",
                "h3", "Bf5",
                "Bd3", "Bxd3",
                "Qxd3", "Rd8",
                "O-O", "Qe6",
                "c5", "Nd7",
                "Ne2", "Bf6",
                "Rfd1", "Nf8",
                "Qc2", "Ng6",
                "Rd2", "Nh4",
                "Rad1", "Be7",
                "Ng3", "f5",
                "f4", "exf4",
                "exf4", "Qe3+",
                "Kh2", "Qxf4",
                "Re2", "Qc7",
                "Be5", "Qd7",
                "Nh5", "Bf8",
                "Rd3", "Ng6",
                "Bd4", "Re8",
                "Rf2", "Re4",
                "Qc3", "Rae8",
                "Rdf3", "Qc7+",
                "Kg1", "Nh4",
                "Rg3", "Re1+",
                "Kh2", "Ng6",
                "Rxf5", "Rd1",
                "Bf2", "Re5",
                "Rxf8+", "Kxf8",
                "Qf3+", "Kg8",
                "Qxd1", "Rf5",
                "Kg1", "Rf5",
                "Re3", "Qf7",
                "Bg3", "h5",
                "Qd1", "Kh7",
                "Qe2", "Qf6",
                "Re6", "Qa1+",
                "Kh2", "Qxa3",
                "Rxc6", "Qxb4",
                "Qe6", "Rg5",
                "Rc8", "h4",
                "Qg8+", "Kh6",
                "Bf2", "Qf4+",
                "Kg1", "Qf3",
                "g3", "Qd1+",
                "Kg2"
            ],
            'A17': [
                "c4", "g6",
                "Nc3", "Bg7",
                "d4", "c5",
                "d5", "Nf6",
                "e4", "d6",
                "Bd3", "O-O",
                "f4", "a6",
                "Nge2", "b5",
                "cxb5", "axb5",
                "Nxb5", "Ba6",
                "Nec3", "c4",
                "Bc2", "Bxb5",
                "Nxb5", "Qa5+",
                "Nc3", "Nfd7",
                "Qf3", "Na6",
                "O-O", "Nb4",
                "Qe2", "Nc5",
                "Be3", "Nbd3",
                "Bxd3", "Nxd3",
                "e5", "dxe5",
                "fxe5", "Bxe5",
                "Bh6", "Rfb8",
                "Qf3", "f5",
                "g4", "Rxb2",
                "gxf5", "Qxc3",
                "fxg6", "Qd4+"
            ],
            'B10': [
                "e4", "c6",
                "d4", "d5",
                "e5", "Bf5",
                "Bd3", "Bxd3",
                "Qxd3", "e6",
                "Nf3", "Qa5+",
                "Bd2", "Qa6",
                "Nc3", "Ne7",
                "O-O", "Nf5",
                "a3", "h5",
                "b4", "Qxd3",
                "cxd3", "Be7",
                "Na4", "g5",
                "Bxg5", "Bxg5",
                "Nxg5", "Nxd4",
                "Nc5", "b6",
                "Na4", "Nd7",
                "f4", "Rg8",
                "Nh3", "Ke7",
                "Ra2", "a5",
                "Rfa1", "Ra6",
                "Kf2", "Rga8",
                "Ng1", "b5",
                "Nc3", "Nb3",
                "Rb1", "axb4",
                "Nxb5", "cxb5",
                "Rxb3", "Rxa3",
                "Rbxa3", "bxa3",
                "Ne2", "Nc5",
                "Nd4", "Nxd3+",
                "Ke3", "Nb4",
                "Ra1", "a2",
                "Kd2", "Rc8",
                "Nxb5", "Rc2+",
                "Ke3", "Rxg2"
            ],
            'B20': [
                "e4", "c5", 
                "Nf3", "d6", 
                "d4", "cxd4", 
                "Nxd4", "Nf6",
                "Nc3", "a6", 
                "Be2", "e6", 
                "O-O", "Be7", 
                "f4", "O-O",
                "Kh1", "Qc7", 
                "a4", "Nc6", 
                "Be3", "Re8", 
                "Bf3", "Rb8",
                "Qd2", "Bd7", 
                "Nb3", "b6", 
                "g4", "Bc8", 
                "g5", "Nd7",
                "Qf2", "Bf8", 
                "Bg2", "Bb7", 
                "Rad1", "g6", 
                "Bc1", "Rbc8",
                "Rd3", "Nb4", 
                "Rh3", "Bg7", 
                "Be3", "Re7", 
                "Kg1", "Rce8",
                "Rd1", "f5", 
                "gxf6", "Nxf6", 
                "Rg3", "Rf7", 
                "Bxb6", "Qb8",
                "Be3", "Nh5", 
                "Rg4", "Nf6", 
                "Rh4", "g5", 
                "fxg5", "Ng4",
                "Qd2", "Nxe3", 
                "Qxe3", "Nxc2", 
                "Qb6", "Ba8", 
                "Rxd6", "Rb7",
                "Qxa6", "Rxb3", 
                "Rxe6", "Rxb2", 
                "Qc4", "Kh8", 
                "e5", "Qa7+",
                "Kh1", "Bxg2+", 
                "Kxg2", "Nd4+"
            ],
            'C00': [
                "e4", "e6",
                "d4", "d5",
                "e5", "c5",
                "c3", "Nc6",
                "Nf3", "Bd7",
                "Be2", "Nge7",
                "O-O", "Nf5",
                "dxc5", "Bxc5",
                "Bd3", "Nfe7",
                "Nbd2", "Ng6",
                "Nb3", "Bb6",
                "Re1", "O-O",
                "Nbd4", "Bc7",
                "Bxg6", "fxg6",
                "Qe2", "Nxd4",
                "cxd4", "h6",
                "h4", "Bb6",
                "Bd2", "Rc8",
                "Rac1", "Qe7",
                "Qd3", "Qf7",
                "Bb4", "Rfe8",
                "Bc5", "Ba5",
                "Red1", "a6",
                "Qa3", "Bd8",
                "Qb4", "Bb5",
                "Re1", "Qf4",
                "Rc3", "Rc7",
                "a4", "Bc6",
                "Bb6", "Rf7",
                "Bxd8", "Rxd8",
                "Ree3", "Rdf8",
                "Rc2", "Qg4",
                "Kh2", "Rf4",
                "b3", "g5",
                "hxg5", "hxg5",
                "Qe7", "Qf5",
                "Nxg5", "Re8",
                "Rxc6", "Rh4+",
                "Rh3", "Rxh3+",
                "gxh3", "Qxf2+",
                "Kh1", "Rxe7",
                "Rc8+", "Qf8",
                "Rxf8+", "Kxf8",
                "Kg2", "Re8",
                "Kf3", "Ke7",
                "Kg4", "Rc8",
                "Kh5", "Rc3",
                "Kg6", "Rd3"
            ],
            'D10': [
                "d4", "Nf6",
                "Nf3", "d5",
                "c4", "c6",
                "Nc3", "Bf5",
                "Qb3", "Qb6",
                "Qxb6", "axb6",
                "cxd5", "Nxd5",
                "Nxd5", "cxd5",
                "e3", "Nc6",
                "Bd2", "Bd7",
                "Be2", "e6",
                "O-O", "Bd6",
                "Rfc1", "Ke7",
                "Bc3", "Rhc8",
                "a3", "Na5",
                "Nd2", "f5",
                "g3", "b5",
                "f3", "Nc4",
                "Bxc4", "bxc4",
                "e4", "Kf7",
                "e5", "Be7",
                "f4", "b5",
                "Kf2", "Ra4",
                "Ke3", "Rca8",
                "Rab1", "h6",
                "Nf3", "g5",
                "Ne1", "Rg8",
                "Kf3", "gxf4",
                "gxf4", "Raa8",
                "Ng2", "Rg4",
                "Rg1", "Rag8",
                "Be1", "b4",
                "axb4", "Ba4",
                "Ra1", "Bc2",
                "Bg3", "Be4+",
                "Kf2", "h5",
                "Ra7", "Bxg2",
                "Rxg2", "h4",
                "Bxh4", "Rxg2+",
                "Kf3", "Rxh2",
                "Bxe7", "Rh3+",
                "Kf2", "Rb3",
                "Bg5", "Kg6",
                "Re7", "Rxb2+",
                "Kf3", "Ra8",
                "Rxe6+", "Kh7"
            ],
            'E12': [
                "d4", "Nf6",
                "c4", "e6",
                "Nf3", "b6",
                "g3", "Bb7",
                "Bg2", "g6",
                "O-O", "Bg7",
                "Nc3", "Ne4",
                "Nxe4", "Bxe4",
                "Bg5", "Qc8",
                "Qd2", "h6",
                "Bf4", "d6",
                "Rac1", "Nd7",
                "Rfe1", "Qb7",
                "b3", "g5",
                "Be3", "f5",
                "Red1", "O-O",
                "Bf1", "Rae8",
                "Ne1", "e5",
                "dxe5", "Nxe5",
                "f3", "Bc6",
                "Bd4", "f4",
                "gxf4", "Rxf4",
                "Be3", "Rf7",
                "Bf2", "Qc8",
                "Bg3", "Qf5",
                "Nc2", "Qxf3",
                "exf3", "Nxf3+",
                "Kh1", "Nxd2+",
                "Bg2", "Bxg2+",
                "Kxg2", "Re2+",
                "Kh1", "Nf3",
                "Nb4", "a5",
                "Rc2", "Rfe7",
                "Nd5", "Rxc2",
                "Nxe7+", "Kf7",
                "Nd5", "h5",
                "Rf1", "g4",
                "Nxc7", "Be5",
                "Rf2", "Rc1+",
                "Kg2", "Rxg1#"
            ],
            'E60': [
                "c4", "Nf6",
                "Nc3", "g6",
                "d4", "Bg7",
                "e4", "d6",
                "Nf3", "O-O",
                "Be2", "e5",
                "d5", "Nbd7",
                "O-O", "Nc5",
                "Qc2", "a5",
                "Ne1", "Ne8",
                "Be3", "f5",
                "exf5", "gxf5",
                "f4", "e4",
                "Qd2", "Nf6",
                "Nc2", "Bd7",
                "Bd4", "Qe8",
                "Ne3", "Qg6",
                "b3", "h5",
                "Ncd1", "Ng4",
                "Bxg7", "Qxg7",
                "Nf2", "Nxf2",
                "Kxf2", "h4",
                "Kg1", "Kf7",
                "Rac1", "Ke7",
                "Rc3", "Rg8",
                "Rf2", "Na6",
                "Nc2", "Nb4",
                "a3", "Nxc2",
                "Rxc2", "c5",
                "dxc6", "bxc6",
                "Rc1", "Rgb8",
                "Rd1", "Qf6",
                "Qe3", "c5",
                "Rd5", "Be6",
                "Rd2", "a4",
                "b4", "cxb4",
                "c5", "d5",
                "c6", "Qc3",
                "Bd3", "d4",
                "Qh3", "Rh8",
                "Rd1", "exd3",
                "Rxd3", "Qxc6",
                "Rxd4", "b3",
                "Re2", "Kf7",
                "Rd1", "Rad8",
                "Rde1", "Qb6+",
                "Kh1", "b2",
                "Rb1", "Rd1+",
                "Rxd1", "b1=Q",
                "Rd2", "Q1b3",
                "Rd3", "Rd8",
                "Rxd8", "Qxh3",
                "gxh3", "Qe3",
                "R8d3", "Qxf4",
                "Kg2", "Bc8",
                "Kg1", "Qe4",
                "Kf2", "Bb7",
                "Rd7+", "Ke6",
                "R1d6+", "Ke5",
                "Rd3", "Qg2+",
                "Ke1", "Be4",
                "Re3", "Qg1+",
                "Ke2", "Qxh2+",
                "Ke1", "Kf4",
                "Rc3", "Qb2",
                "Rdc7", "Bf3",
                "R7c4+", "Kg3",
                "Rc2", "Qxa3",
                "R4c3", "Qe7+",
                "Kf1", "Qe4",
                "Rg2+", "Kxh3",
                "Re3", "Qb1+"
            ],
        }
        return model_games.get(eco_code, [])
    
def _get_white_player(eco_code: str) -> str:
    white_players = {
        'E00': "Vladimir Kramnik",
        'A10': "Anatoly Karpov",
        'D02': "Tigran Petrosian",
        'C39': "Alexander Alekhine",
        'C44': "Garry Kasparov",
        'C21': "Alexander Alekhine",
        'C50': "Emanuel Lasker",
        'C60': "Boris Spassky",
        'D00': "Magnus Carlsen",
        'A20': "Lajos Portisch",
        'A34': "Juergen Beikert",
        'A17': "Román Hernández",
        'B10': "Givi Gamrekeli",
        'B20': "Anatoly Karpov",
        'C00': "Faustino Oro",
        'D10': "David Janowski",
        'E12': "Jon Ludvig Hammer",
        'E60': "James Sherwin"
    }
    return white_players.get(eco_code, [])
    
def _get_black_player(eco_code: str) -> str:
    black_players = {
        'E00': "Magnus Carlsen",
        'A10': "Oleg Romanishin",
        'D02': "Alexander Chistiakov",
        'C39': "Stefan Levitsky",
        'C44': "Nigel Short",
        'C21': "Arturo Pomar",
        'C50': "Wilhelm Steinitz",
        'C60': "Svetozar Gligoric",
        'D00': "Ding Liren",
        'A20': "Boris Spassky",
        'A34': "Vladimir Kramnik",
        'A17': "Garry Kasparov",
        'B10': "Tigran Petrosian",
        'B20': "Garry Kasparov",
        'C00': "Viswanathan Anand",
        'D10': "José Raúl Capablanca",
        'E12': "Magnus Carlsen",
        'E60': "Bobby Fischer"
    }
    return black_players.get(eco_code, [])